### ISSUE TITLE
Some games not working (the executable fails to launch)

### ISSUE THREAD

**Issue by pedropsi** [Narkhos/Puzzlescript-Wrapper#2]
[Skilleblokker](https://pedropsi.github.io/skilleblokker#lfodp) and [Play Mini Gemini Replay](https://pedropsi.github.io/pmgrp#lfodp) cause the executable to launch and close immediately. Possibly some of the used character symbols are not accepted?

**Comment by Narkhos** [comment]
For some reason, in both games it say that P is not defined.
replacing
P = Player and D
by 
P = Player and PlayerDrop
seems to fix "Play Mini Gemini Replay" (I don't know if it changes behaviour of the game)

**Comment by Narkhos** [comment]
For Skilleblokker, replacing
P = Agent and Player1 and TickTime
by
P = Player and Player1 and TickTime
allow to skip the first error but then I end up with an encoding error.
I must investigate on this.

**Comment by Narkhos** [comment]
I fixed it. The problem was the puzzlescript version I was using. With the last version everything seems OK
I will do a new release as soon as possible with this fix. If you want to give it a try in the meantime, you just have to replace ./data/js by the one in v8 branch : https://github.com/Narkhos/Puzzlescript-Wrapper/tree/v8/v8PuzzlescriptWrapper/data/js

**Comment by pedropsi** [comment]
It's working perfectly now. Great work!
